imageCredentials:
  registry: registry.gitlab.com
  username: registry_user
  password: nQGb5sxxWmuWswRjL1_x

host: todo
domain: web.ryoma0923.work

todo:
  environment: production
  django:
    settings: sampleapp.settings_mysql
  server:
    image: registry.gitlab.com/fufuhu/ti_rancher_k8s_sampleapp/todo/server
    tag: latest
    replicas: 1


# MySQL対応のためのValues部分

mysql:
  mysqlUser: todo
  mysqlPassword: todo
  mysqlDatabase: todo
  configurationFiles:
    mysqld_custom.cnf: |-
      [mysqld]
      pid-file        = /var/run/mysqld/mysqld.pid
      socket          = /var/run/mysqld/mysqld.sock
      datadir         = /var/lib/mysql
      log-error       = /var/log/mysql/error.log
      # Disabling symbolic-links is recommended to prevent assorted security risks
      symbolic-links=0
      character-set-server=utf8 
      collation-server=utf8_unicode_ci