apiVersion: v1
kind: Service
metadata:
  name: service-repository
  labels:
    app: repository
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: repository