apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-repository
  labels:
    app: repository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: repository
  template:
    metadata:
      labels:
        app: repository
    spec:
      containers:
      - image: {{ .Values.repository.image }}:{{ .Values.repository.tag }}
        name: deployment-repository
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      imagePullSecrets:
        - name: secret-repository
